name : Terraform Deployment
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      - name: Terraform Init
        run: terraform init
      
      - name: Initialize Terraform with S3 Backend
        run: terraform init -backend-config="key=terraform.tfstate"  
        
      - name: terraform plan
        run: terraform plan
        
      - name: List Terraform State (Check if Resources Exist)
        run: terraform state list

      - name: Terraform Destroy (Remove All Resources)
        run: terraform destroy -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


      
      