name: Terraform Destroy

on:
  workflow_dispatch:  # Allows manual execution

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4   

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Remove Old Lock Files (Fix Issues)
        run: rm -rf .terraform .terraform.lock.hcl

      - name: Initialize Terraform with Backend
        run: terraform init -backend-config="key=terraform.tfstate"

      - name: List Terraform State (Check if Resources Exist)
        run: terraform state list

      - name: Terraform Plan for Destroy (Check Before Running)
        run: terraform plan -destroy

      - name: Terraform Destroy (Remove All Resources)
        run: terraform destroy -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
