name: Terraform Destroy

on:
  workflow_dispatch:  # Allows manual execution from GitHub UI

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # Use your required Terraform version

      - name: Initialize Terraform
        run: terraform init
        
      - name: List Terraform State
        run: terraform state list

      - name: Terraform Plan for Destroy
        run: terraform plan

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
